In [3]:
'''
Descripttion: numpy广播实现计算多个anchor和gtbox的iou
version: 1.0
Author: SongJ
Date: 2021-09-11 09:05:17
LastEditors: SongJ
LastEditTime: 2021-09-12 22:23:25
'''

import numpy as np

In [17]:
def box_iou(boxes1,boxes2):
    # boexs1.shape(boxes1的数量,xyxy)
    # boexs2.shape(boxes2的数量,xyxy)

    # 计算面积,areas.shape(boxes的数量,)
    box_area = lambda boxes : ((boxes[:,3]-boxes[:,1]) * (boxes[:,2]-boxes[:,0]))
    areas1, areas2 = box_area(boxes1),box_area(boxes2)

    #取相交部分的坐标值,利用广播机制,shape(boxes1的数量,boxes2的数量,2)
    interuppeerleft = np.maximum(boxes1[:,None,:2],boxes2[:,:2]) # 左上角坐标
    interlowerright = np.minimum(boxes1[:,None,2:],boxes2[:,2:]) # 右下角坐标

    #计算相交部分的面积,shape(boxes1的数量,boxes2的数量,2)
    inter = (interlowerright - interuppeerleft).clip(min=0) # 做差有负数表示不相交,直接设置为0
    # shape(boxes1的数量,boxes2的数量)
    interarea = inter[:,:,0] * inter[:,:,1] 

    # 计算并积,shape(boxes1的数量,boxes2的数量)
    unionarea = areas1[:,None] + areas2 - interarea
    return interarea/unionarea




In [3]:
a = np.array([2,3])
b = np.array([3,2])


In [4]:
a[:,None] + b

array([[5, 4],
       [6, 5]])

In [5]:
a

array([2, 3])

In [19]:
a = np.random.randint(1,5,[5,4])
b = np.random.randint(1,5,[3,4])


/home/songj/miniconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in true_divide


(5, 3)

In [20]:
interuppeerleft = np.maximum(a[:,None,:2],b[:,:2]) # 左上角坐标
interlowerright = np.minimum(a[:,None,2:],b[:,2:]) # 右下角坐标

In [21]:

inter =  (interlowerright - interuppeerleft).clip(min=0)


In [23]:
inter[:,:,0] * inter[:,:,1] 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
inter[:,:,0]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])